version: "3.3"
services:
  nginx:
    command: /bin/bash -c "\
      while :; do \
        sleep 12h & wait $${!}; \
        nginx -s reload; \
      done & \
      nginx -g \"daemon off;\" \
      "
    volumes:
      - /etc/ssl/odkx:/etc/ssl/odkx
configs:
  com.nginx.sync-endpoint.conf:
    file: ./config/nginx/sync-endpoint-https.conf
